import React from "react";
import Head from "next/head";
import ProductCard from "../common/ProductCard";

export const getServerSideProps = async () => {
  const response = await fetch("https://fakestoreapi.com/Products");
  const data = await response.json();
  return {
    props: { productData: data },
  };
};

const Courses = (props) => {
  const { productData } = props;
  console.log(productData);
  return (
    <>
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <div className="row mt-4 mb-4">
          <div className="col-12">
            <h2>Welcome to Courses page!</h2>
          </div>
        </div>
      </div>
      <div className="container">
        <div className="row">
          {productData.map((item) => (
            <div className="col-md-3" key={item.id}>
              <div className="card mb-4" style={{ width: "100%" }}>
                <div className="card-img-top p-4">
                  <img
                    src={item.image}
                    alt={item.title}
                    width={205}
                    height={270}
                  />
                </div>
                <div className="card-body">
                  <h5
                    className="card-title"
                    style={{
                      display: "-webkit-box",
                      webkitLineClamp: "1",
                      webkitBoxOrient: "vertical",
                      overflow: "hidden",
                    }}
                  >
                    {item.title}
                  </h5>
                  <p
                    className="card-text"
                    style={{
                      display: "-webkit-box",
                      webkitLineClamp: "2",
                      webkitBoxOrient: "vertical",
                      overflow: "hidden",
                    }}
                  >
                    {item.description}
                  </p>
                  <p style={{ fontWeight: "bold" }}>$ {item.price}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Courses;
